version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working-directory: ~/ci-test
    docker:
      -image: circleci/python3.7.4
      environment:
        PIPENV_VENV_IN_PROJECT: true
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./add_test.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
