version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working-directory: ~/ci-test
    docker:
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python add_test.py test

workflows:
  main:
    jobs:
      - build-and-test
